apiVersion: v1
kind: Service
metadata:
  labels:
    app: php-application
  name: php-application
  namespace: php
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: php-application
  type: ClusterIP